name: Deploy Docusaurus to GitHub Pages

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        working-directory: spoon-cookbook
        run: npm ci --no-audit --no-fund

      - name: Build website
        working-directory: spoon-cookbook
        run: npm run build

      - name: Deploy to GitHub Pages
        working-directory: spoon-cookbook
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npx docusaurus deploy --yes


